(function() {var implementors = {};
implementors["rusoto_core"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html\" title=\"struct std::ffi::os_str::OsStr\">OsStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://docs.rs/openssl/0.9/openssl/x509/struct.X509Ref.html\" title=\"struct openssl::x509::X509Ref\">X509Ref</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://docs.rs/openssl/0.9/openssl/ssl/struct.SslSessionRef.html\" title=\"struct openssl::ssl::SslSessionRef\">SslSessionRef</a>",];
implementors["rusoto_s3"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/c_str/struct.CStr.html\" title=\"struct std::ffi::c_str::CStr\">CStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/ffi/os_str/struct.OsStr.html\" title=\"struct std::ffi::os_str::OsStr\">OsStr</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/path/struct.Path.html\" title=\"struct std::path::Path\">Path</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://docs.rs/openssl/0.9/openssl/x509/struct.X509Ref.html\" title=\"struct openssl::x509::X509Ref\">X509Ref</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/collections/borrow/trait.ToOwned.html\" title=\"trait collections::borrow::ToOwned\">ToOwned</a> for <a class=\"struct\" href=\"https://docs.rs/openssl/0.9/openssl/ssl/struct.SslSessionRef.html\" title=\"struct openssl::ssl::SslSessionRef\">SslSessionRef</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
