(function() {var implementors = {};
implementors["rusoto_core"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for &amp;'a <a class=\"struct\" href=\"https://docs.rs/openssl/0.9/openssl/bn/struct.BigNum.html\" title=\"struct openssl::bn::BigNum\">BigNum</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://docs.rs/openssl/0.9/openssl/bn/struct.BigNum.html\" title=\"struct openssl::bn::BigNum\">BigNum</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for &amp;'a <a class=\"struct\" href=\"https://docs.rs/openssl/0.9/openssl/bn/struct.BigNumRef.html\" title=\"struct openssl::bn::BigNumRef\">BigNumRef</a>",];
implementors["rusoto_s3"] = ["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for &amp;'a <a class=\"struct\" href=\"https://docs.rs/openssl/0.9/openssl/bn/struct.BigNum.html\" title=\"struct openssl::bn::BigNum\">BigNum</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://docs.rs/openssl/0.9/openssl/bn/struct.BigNum.html\" title=\"struct openssl::bn::BigNum\">BigNum</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for &amp;'a <a class=\"struct\" href=\"https://docs.rs/openssl/0.9/openssl/bn/struct.BigNumRef.html\" title=\"struct openssl::bn::BigNumRef\">BigNumRef</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html\" title=\"trait core::ops::Neg\">Neg</a> for <a class=\"struct\" href=\"https://doc.rust-lang.org/time/time/duration/struct.Duration.html\" title=\"struct time::duration::Duration\">Duration</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
